# Generated by Django 4.0.4 on 2022-05-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='account',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
